name: Update Recent Work Updates

on: push # 모든 브랜치에 대한 푸시 이벤트에 반응

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # 모든 히스토리를 가져옵니다
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyGithub
    - name: Update Recent Work Updates
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: python .github/scripts/update_recent_works.py
